#!/usr/bin/env python3
"""
Builder OS -- Test A collection.

Run after Codex has finished. Validates the project and the run record,
generates RESULT.md, and updates the benchmark.

    python scripts/finish-test-a.py
    python scripts/finish-test-a.py --run validation/runs/A1

Reuses scripts/validate.py entirely -- this is a wrapper, not a second
validation system. It reports what happened. It does not judge whether the
work is good, and it produces no score.
"""

import os
import re
import sys
import glob
import datetime
import importlib.util

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUNS_DIR = os.path.join(ROOT, "validation", "runs")

spec = importlib.util.spec_from_file_location("bosvalidate",
                                              os.path.join(ROOT, "scripts", "validate.py"))
V = importlib.util.module_from_spec(spec)
spec.loader.exec_module(V)

BAR = "-" * 64


def latest_run():
    dirs = [d for d in glob.glob(os.path.join(RUNS_DIR, "A*"))
            if os.path.isdir(d) and os.path.exists(os.path.join(d, "run.md"))]
    if not dirs:
        print("\nNo Test A run found. Run this first:\n\n    python scripts/setup-test-a.py\n")
        sys.exit(1)
    return sorted(dirs, key=lambda d: int(re.sub(r"\D", "", os.path.basename(d)) or 0))[-1]


def project_from_run(text):
    m = re.search(r"^>\s*Project:\s*`([^`]+)`", text, re.M)
    return m.group(1) if m else None


def capture(text, header):
    m = re.search(r"###\s+" + re.escape(header) + r"(.*?)(?=\n###\s|\n##\s|\Z)", text, re.S)
    return m.group(1).strip() if m else ""


def filled(section):
    """A section still full of <placeholders> has not been filled in."""
    stripped = re.sub(r"`?<[^>]*>`?", "", section)
    return len(stripped.split()) > 8


def build_result(run_id, run_file, project, problems, events, observations, metrics):
    text = V.read(run_file)
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    routing = capture(text, "Routing result")
    docs = capture(text, "Documents Builder OS created")
    state = capture(text, "Runtime state after the run")
    devs = capture(text, "Deviations from documented behaviour")
    comp = capture(text, "The comparison")
    baseline = re.search(r"##\s+Baseline(.*?)(?=\n##\s|\Z)", text, re.S)
    baseline = baseline.group(1).strip() if baseline else ""

    def evs(kind):
        rows = [e for e in events if e["type"] == kind]
        if not rows:
            return "_None recorded. Empty is a valid result._"
        return "\n".join(f"- **{e['stage']}** — {e['desc']}  ·  `{e['evidence']}`" for e in rows)

    q = [e for e in events if e["type"] == "QUESTION"]
    b = metrics["MEASURED  b_class_questions"]

    out = f"""# TEST A RESULT — {run_id}

> Generated by `scripts/finish-test-a.py` on {now}. Regenerating overwrites this file;
> the run record is the source of truth.

**Project:** `{project or "not recorded"}`
**Run record:** `{os.path.relpath(run_file, ROOT)}`

The four sections below are **never collapsed into one number.** They are different
kinds of evidence and mixing them would hide which is which.

---

## PROVEN

*Deterministic. Derived from files by the checker. Reproducible.*

| Check | Result |
|---|---|
| Run record + project structure | {"**FAIL** — see below" if problems else "**PASS**"} |
| Documents present | `{observations.get("documents_present", "not checked")}` |
| Conditional documents created | `{observations.get("conditional_documents_created", [])}` |
| Runtime stage | `{observations.get("state_stage", "—")}` |
| Last gate passed | `{observations.get("state_gate", "—")}` |
| Next prompt | `{observations.get("state_next_prompt", "—")}` |

### Counts

| Metric | Value |
|---|---|
"""
    for k, v in metrics.items():
        cls, name = k.split(None, 1)
        out += f"| {name.strip()} _{cls}_ | {v} |\n"

    out += f"""
**Handoff re-derivations (B-class): {b}** — target ≤2. {"PASS" if b <= 2 else "OVER TARGET"}

*Test A ends before a handoff, so a B-count of 0 here means "not exercised", not "perfect".*
"""

    if problems:
        out += "\n### Structural problems\n\n" + "\n".join(f"- {p}" for p in problems) + "\n"

    out += f"""
---

## OBSERVED

*What actually happened. Real, but not reproducible.*

### Routing

{routing if filled(routing) else "_Not filled in. **This is the primary measurement of Test A** — without it the run cannot answer whether routing worked._"}

### Documents

{docs if filled(docs) else "_Not filled in._"}

### Runtime state

{state if filled(state) else "_Not filled in._"}

### Deviations from documented behaviour

{devs if filled(devs) else "_None recorded._"}

### Friction

{evs("FRICTION")}

### Value

{evs("VALUE")}

### Questions asked

{chr(10).join(f"- **class {e.get('qclass','?')}** — {e['desc']}  ·  `{e['evidence']}`" for e in q) if q else "_None recorded._"}

---

## HUMAN JUDGEMENT

*Yours alone. Never scored, never aggregated.*

### Baseline, captured before the run

{baseline if filled(baseline) else "_**Missing.** Without a baseline captured beforehand there is no control, and this run cannot show what Builder OS changed._"}

### Baseline vs Builder OS

{comp if filled(comp) else "_Not filled in._"}

Three questions only you can answer:

1. **Was the direction meaningfully different from your baseline?**
2. **Was the difference desirable** — or merely different?
3. **Did Builder OS prevent a default solution you would otherwise have shipped?**

> One instance of *"it made me reject X before I built it, and the replacement was
> better"* outweighs every count above.

---

## UNPROVEN

*Test A cannot reach these. Recording them stops a passing run from implying more
than it showed.*

| Not tested | Needs |
|---|---|
| Handoff sufficiency | Test B — a real `HANDOFF.md` consumed by a fresh session |
| Implementation fidelity to the thesis | Cursor, a multi-file build |
| Independent review | A separate session with no build context |
| Browser QA catching a real defect | A built artifact |
| Accessibility · performance · deployment | A built artifact |
| Provider switching | A second provider |
| Long-session behaviour, drift | Hours of real work |
| **Design quality** | **An independent reviewer. Never self-assessed.** |

---

## Recommendation

**Did this run produce enough evidence to change Builder OS?**

`<NO — FREEZE>` or `<YES — smallest change: …>`

> One occurrence is rarely enough. The loop in `templates/RETROSPECTIVE.md` requires a
> lesson to recur, or to have cost something nameable in hours. **After a first run,
> "freeze" is the expected answer** — and a run that changes nothing is still a run
> that told you something.
"""
    return out


def main():
    args = sys.argv[1:]
    run_dir = args[args.index("--run") + 1] if "--run" in args else latest_run()
    run_file = os.path.join(run_dir, "run.md") if os.path.isdir(run_dir) else run_dir
    if not os.path.exists(run_file):
        print(f"\nNo run record at {run_file}\n")
        return 1

    text = V.read(run_file)
    project = project_from_run(text)
    run_id = V.field(text, "Run ID") or os.path.basename(run_dir)

    print()
    print(BAR)
    print(f"BUILDER OS  --  TEST A COLLECTION  ({run_id})")
    print(BAR)
    print()

    problems, events = V.check_run_file(text, run_file)
    observations = {}
    if project and os.path.isdir(project):
        p2, observations = V.check_project(project, V.field(text, "Mode"), None)
        problems += p2
    elif project:
        problems.append(f"project directory not found: {project}")
    problems += V.check_mode_drift()

    metrics = V.compute_metrics(events, observations)

    result_path = os.path.join(run_dir, "RESULT.md")
    with open(result_path, "w", encoding="utf-8") as f:
        f.write(build_result(run_id, run_file, project, problems, events, observations, metrics))

    for k, v in metrics.items():
        print(f"  {k}: {v}")

    # Name them. A count alone is not actionable -- the point of this metric is
    # to notice ceremony, which means knowing WHICH document appeared.
    extra = observations.get("conditional_documents_created", [])
    if extra:
        print("")
        print(f"  Conditional documents created: {extra}")
        print("  Each should have been triggered by a stated rule, not by habit.")
    print()
    if problems:
        print(f"  {len(problems)} structural problem(s):")
        for p in problems:
            print(f"    - {p}")
    else:
        print("  Structure: OK")
    print()

    print(BAR)
    print("BENCHMARK")
    print(BAR)
    V.benchmark()
    print()

    print(BAR)
    print("BRING THESE BACK FOR ANALYSIS")
    print(BAR)
    print(f"  {os.path.relpath(result_path, ROOT)}")
    print(f"  {os.path.relpath(run_file, ROOT)}")
    print(f"  {os.path.relpath(os.path.join(run_dir, 'evidence'), ROOT)}/")
    if project:
        print("")
        print(f"  Conditional documents created: {extra}")
        print("  Each should have been triggered by a stated rule, not by habit.")
        print(f"  {project}   (the project itself)")
    print()
    print("  RESULT.md separates PROVEN / OBSERVED / HUMAN JUDGEMENT / UNPROVEN.")
    print("  There is no overall score, deliberately -- a score would let a")
    print("  good-looking run stand in for a good project.")
    print()
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
